### ISSUE TITLE
Creating new Maven targets in Sidebar

### ISSUE THREAD

**Issue by Ninerian** [nlloyd/SublimeMaven#10]
i integrated    

"maven_menu_commands":
    [
        { "caption": "Maven: Run test", "command": "maven", "args": {"paths": [], "goals": ["test"]} },
        { "caption": "Maven: Run install", "command": "maven", "args": {"paths": [], "goals": ["install"]} },
        { "caption": "Maven: Run clean test", "command": "maven", "args": {"paths": [], "goals": ["clean", "test"]} },
        { "caption": "Maven: Run clean install", "command": "maven", "args": {"paths": [], "goals": ["clean", "install"]} }
    ]

into my Preference.sublime-settings but it doesnt had any impact on the sidebarmenu. How do I have to integrate it?

**Comment by nlloyd** [comment]
That is, or at least should be, correct.  I just verified that this feature is no longer working so I will investigate.  Should have this fixed by tomorrow.

**Comment by nlloyd** [comment]
I believe this has been fixed, but please reopen this if it still doesn't work.

**Comment by Ninerian** [comment]
It worked. But today I loaded sublime and saw the default maven options again. Did you change something?
I cannot reopen it.

**Comment by nlloyd** [comment]
Nothing changed but I have a suspicion that it may be timing related.  Opening the issue again.
