### ISSUE TITLE
Installing plugin breaks build system auto-detect for Java

### ISSUE THREAD

**Issue by justbrian** [nlloyd/SublimeMaven#18]
I have noticed after installing ST2 on a couple of machines recently that installing SublimeMaven prevents the default build system auto-detect.

E.g,,
1. Install ST2
2. Create a .java file.
3. With Build System set to default "Automatic", default Build shortcut builds/compiles correctly using autodetected javac
4. Install SublimeMaven
5. Default build shortcut on same file now says "No pom.xml found...", even though build system "Automatic" is selected

In both cases no project is defined. I would expect being able to leave the Build system as "Automatic", and .java files to build with javac as before, and no error produced by the default shortcut.

**Comment by nlloyd** [comment]
I experimented with the Automatic build detection mechanism and found that even the base install of Sublime Text 2 is not smart enough to differentiate between a "JavaC" project and an "Ant" project (JavaC is chosen regardless of the presence of a build.xml file).  Unfortunately that means the only real "fix" I can provide right now is to disable the maven build system but leave it around for anyone who wants to use it.  I will look for an alternative solution but for now this is the best I can do.
