### ISSUE TITLE
MAVEN_OPTS

### ISSUE THREAD

**Issue by Chrisdo82** [nlloyd/SublimeMaven#21]
Is there a way to make use of MAVEN_OPTS with your plugin?

**Comment by nlloyd** [comment]
That SHOULD be a system level setting.  Though I could integrate that into the plugin somehow.  Were you thinking in user settings or something else?

**Comment by Chrisdo82** [comment]
I tried, but it didn't work for me. The user settings were exactly what I was thinking.

**Comment by nlloyd** [comment]
Implemented support for overriding/adding environment variables to maven subprocess.  Check the README.md.  Involves putting stuff into a user settings file "Maven.sublime-settings".  Let me know if this works!  Updated and tested in Sublime Text 2 and 3 versions of this plugin.
