### ISSUE TITLE
Does this plugin work with windows?

### ISSUE THREAD

**Issue by shefalijoshi** [nlloyd/SublimeMaven#22]
I tried to install this with the windows version of sublime text 3, but the plugin did not work.
Has it been tested with windows?

**Comment by nlloyd** [comment]
This should work with windows... though I admittedly have yet to test it (note to self: do that).
What are you seeing in the console?

**Comment by ugrave** [comment]
Hi, i have the same Problem with Sublime 3 and the Maven plugin on Windows 7.

There is an error message  on my console:
File "config_generator in C:\Users\XXX\AppData\Roaming\Sublime Text 3\Installed Packages\Maven.sublime-package", line 74, in generate_config
FileNotFoundError: [Errno 2] No such file or directory: 'C:\Users\XXX\AppData\Roaming\Sublime Text 3\Installed Packages\Maven.sublime-package\Context.sublime-menu'

**Comment by nlloyd** [comment]
Sorry for the rather extreme delay on this, I will take a look this weekend if not sooner and get to working on a fix.

**Comment by tutysara** [comment]
Have the same issue on WIndows 7 with ST3.

  File "config_generator in C:\Users<user>\AppData\Roaming\Sublime Text 3\Installed Packages\Maven.sublime-package", line 74, in generate_config
FileNotFoundError: [Errno 2] No such file or directory: 'C:\Users\<user>\AppData\Roaming\Sublime Text 3\Installed Packages\Maven.sublime-package\Context.sublime-menu'

**Comment by mortea** [comment]
Same problem on Mac OS 10.9.4 as well.
Traceback (most recent call last):
  File "config_generator in /Users/<user>/Library/Application Support/Sublime Text 3/Installed Packages/Maven.sublime-package", line 74, in generate_config
NotADirectoryError: [Errno 20] Not a directory: '/Users/<user>/Library/Application Support/Sublime Text 3/Installed Packages/Maven.sublime-package/Context.sublime-menu'

**Comment by nlloyd** [comment]
This appears to be an issue with how Sublime Package Control is installing the plugin. Investigating a solution now.
