### ISSUE TITLE
Problem when generating projects from pom

### ISSUE THREAD

**Issue by ziggurat** [nlloyd/SublimeMaven#9]
When I try to generate a sublime project from a pom in the folders I got this exception in the sublime console:

Exception in thread Thread-17:
Traceback (most recent call last):
  File ".\threading.py", line 532, in **bootstrap_inner
  File "./utils/mvn/pom.py", line 182, in run
  File "./utils/mvn/pom.py", line 216, in gen_project_name
  File ".\xml\sax__init**.py", line 93, in make_parser
SAXReaderNotAvailable: No parsers found

Using ubuntu 12.04. I could not found a way of making that library available to the plugin. If I just enter a python console and create a sax parser the code works fine.

Any help?

**Comment by nlloyd** [comment]
Wow!  That is a new one on me.  I will create a VM of Ubuntu 12.04 and take a look.
What version of python do you get from the sublime console?

I have only tested this on OS X and Win 7 so far.

**Comment by ziggurat** [comment]
Not sure how to get the version from the sublime console. Here is the console output on sublime startup:

startup, version: 2210 linux x64 channel: stable
executable: /usr/lib/sublime-text-2/sublime_text
working dir: /home/manuel
packages path: /home/manuel/.config/sublime-text-2/Packages
settings path: /home/manuel/.config/sublime-text-2/Settings
PackageSetup not required
Py_GetProgramName(): sublime_text
Py_GetExecPrefix(): .
Py_GetProgramFullPath(): 
Py_GetPath(): ./lib/python26.zip:./lib/python2.6/:./lib/python2.6/plat-linux2:./lib/python2.6/lib-tk:./lib/python2.6/lib-old:./lib/python2.6/lib-dynload
Py_GetPythonHome(): .

**Comment by nlloyd** [comment]
from the console:
import sys
print sys.version

I suspect it is using, like the Mac OS X version does, the system installed python (in Windows it uses an embedded python).

**Comment by ziggurat** [comment]
> > > import sys
> > > print sys.version
> > > 2.6.6 (r266:84292, Jun 16 2011, 22:27:44) 
> > > [GCC 4.4.5]

I think it's bundled as ubuntu 12.04 have version 2.7 installed. I will recheck.

**Comment by nlloyd** [comment]
Finally got a VM setup on my computer at home but have yet to dig deeply into this.  I will see if I can figure it out in the next two days.  At the very least I seem to have an identical environment setup.

**Comment by nlloyd** [comment]
Found the solution through the SublimeXdebug project and added the solution to the readme.  You basically need to grab (or build with expat support) python2.6.x libraries and copy them into SublimeText2/lib directory.  Apparently the packaged python release does not contain expat support.  The other possibility is to do without the xml parsing and do some messy regex but I would rather not.

**Comment by ghost** [comment]
Do you mind providing a link to a ZIP of Python 2.6 with expat support or changing the plugin so it works with the stock editor please?

It would be very much appreciated. I've tried to find/build Python 2.6 with expat support for several hours and failed hard and I'd love to have the config generated from within your plugin.

**Comment by nlloyd** [comment]
I am going to take another whack at this to not require such an ugly fix.

**Comment by nlloyd** [comment]
Finally figured this out.  Ended up using a deprecated but still available xml parsing package within python.  Tested against a 32bit Ubuntu 12.04 VM I have running but let me know if you still see problems.
